title: Homepage
description: I am a really cool person
remote_theme: gayanvirajith/harmony
plugins:
  - jekyll-remote-theme

baseurl: ""
url: "https://RNB-9.github.io"

harmony:
  name: Homepage
  description: I am a really cool person
  meta_description: I am a really cool person
  basetheme: theme-base-01
  author:
    name: Your Name
    email: your@email.com
    url: https://RNB-9.github.io
  google_analytics_key:
  social:
    github: RNB-9
    twitter:
    facebook:
    dribble:
    pinterest:
  show_disclaimer: false

markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - Gemfile
  - README.md
  - .gitignore
  - Gemfile.lock

sass:
  sass_dir: assets/css/_sass
  style: compressed
